world.creatureList ={
    cowBrown:  {region: 'grassland', spriteName:'cowBrown', displayName:'Brown Cow', attack: 5, speed: 5, cost:15},
    cowBlack:  {region: 'grassland', spriteName:'cowBlack', displayName:'Black Cow', attack: 5, speed: 5, cost:10},
    armadillo: {region: 'undefined', spriteName: 'armadillo', displayName: 'Armadillo', attack:5, Speed:5, cost:20},
    antelopeFemale: {region:'undefined', spriteName: 'antelopeFemale', displayName: 'Female Antelope', attack:5, speed:5, cost:25},
    antelopeMale: {region: 'undefined', spriteName: 'antelopeMale', displayName: 'Male Antelope', attack:5, speed:5, cost:25},
    brownColugo: {region: 'undefined', spriteName: 'brownColugo', displayName: 'Brown Colugo', attack:5, speed:5, cost:35},
    brownHorse: {region: 'undefined', spriteName: 'brownHorse', displayName: 'Brown Horse', attack:5, speed:5, cost:35},
    brownLlama: {region: 'undefined', spriteName: 'brownLlama', displayName: 'Brown Llama', attack:5, speed:5, cost:35},
    donkey: {region: 'undefined', spriteName: 'donkey', displayName: 'Donkey', attack:5, speed:5, cost: 35},
    Elephant: {region: 'undefined', spriteName: 'elephant', displayName: 'Elephant', attack:5, speed:5, cost: 40},
    grayDog: {region: 'undefined', spriteName: 'grayDog', displayName: 'Gray Dog', attack:5, speed:5, cost: 40},
    grayHyena: {region: 'undefined', spriteName:'grayHyena', displayName: 'Gray Hyena', attack:5, speed:5, cost:40},
    hyena: {region: 'undefined', spriteName: 'hyena', displayName: 'Hyena', attack:5, speed:5, cost:45},
    lioness: {region:'undefined', spriteName: 'lioness', displayName: 'Lioness', attack:5, speed:5, cost:55},
    moose: {region: 'undefined', spriteName: 'moose', displayName: 'Moose', attack:5, speed:5, cost:55},
    orangeDog: {region: 'undefined', spriteName: 'orangeDog', displayName: 'Orange Dog', attack:5, speed: 5, cost:55},
    redColugo: {region: 'undefined', spriteName: 'redColugo', displayName: 'Red Colugo', attack:5, speed:5, cost:60},
    redFox: {region: 'undefined', spriteName: 'redFox', displayName: 'Red Fox', attack:5, speed:5, cost:65},
    tanAntelopeFemale: {region: 'undefined', spriteName: 'tanAntelopeFemale', displayName: 'Tan Female Antelope', attack:5, speed:5, cost:30},
    tanAntelopeMale: {region: 'undefined', spriteName: 'tanAntelopeMale', displayName: 'Tan Male Antelope', attack:5, speed:5, cost:30},
    tanDog: {region: 'undefined', spriteName: 'tanDog', displayName: 'Tan Dog', attack:5, speed:5, cost:65},
    tanHorse: {region: 'undefined', spriteName: 'tanHorse', displayName: 'Tan Horse', attack:5, speed:5, cost:65},
    tanLlama: {region: 'undefined', spriteName: 'tanLlama', displayName: 'Tan Llama', attack:5, speed:5, cost:65},
    tiger: {region: 'undefined', spriteName: 'tiger', displayName: 'Tiger', attack:5, speed:5, cost:75},
    zebra: {region: 'undefined', spriteName: 'zebra', displayName: 'Zebra', attack:5, speed:5, cost:75},
};